TOKEN_KIND(BooleanLiteral, 0)
TOKEN_KIND(CharacterLiteral, 0)
TOKEN_KIND(UnicodeLiteral, 0)
TOKEN_KIND(IntegerLiteral, 0)
TOKEN_KIND(Real32Literal, 0)
TOKEN_KIND(Real64Literal, 0)
TOKEN_KIND(StringLiteral, 0)
TOKEN_KIND(Identifier, 0)
